services:
  db: 
    image: mysql:8.0.30-debian
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestEvents
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql